question_data = [
    {
        "response_code": 0,
        "results": [
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "\"Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.\" is a grammatically correct sentence.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Kissing someone for one minute burns about 2 calories.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "There are 86400 seconds in a day.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The scientific name for the Southern Lights is Aurora Australis?",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "SCP-173 was the first SCP article written for the web-based collaborative fiction project known as the \"SCP Foundation\"",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "A pencil's lead is typically made from graphite, not lead",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The word \"news\" originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The pickled gherkin was first added to hamburgers because a US health law required all fast-food to include a source of Vitamin C.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The sum of all the numbers on a roulette wheel is 666.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Sitting for more than three hours a day can cut two years off a person's life expectancy.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The commercial UK channel ITV stands for \"International Television\".",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Haggis is traditionally ate on Burns Night.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The French word for \"glass\" is \"glace\".",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "You are allowed to sell your soul on eBay.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Cucumbers are usually more than 90% water.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "An eggplant is a vegetable.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Crystal Pepsi was first sold in US markets in 1993.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "Pure water effectively conducts electricity.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
        ],
    }
]
